// Code generated by MockGen. DO NOT EDIT.
// Source: branch_repository.go
//
// Generated by this command:
//
//	mockgen -source=branch_repository.go -destination=mocks/branch_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/SandaruwanWeerawardhana/pos-backend/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBranchRepository is a mock of BranchRepository interface.
type MockBranchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBranchRepositoryMockRecorder
	isgomock struct{}
}

// MockBranchRepositoryMockRecorder is the mock recorder for MockBranchRepository.
type MockBranchRepositoryMockRecorder struct {
	mock *MockBranchRepository
}

// NewMockBranchRepository creates a new mock instance.
func NewMockBranchRepository(ctrl *gomock.Controller) *MockBranchRepository {
	mock := &MockBranchRepository{ctrl: ctrl}
	mock.recorder = &MockBranchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranchRepository) EXPECT() *MockBranchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBranchRepository) Create(ctx context.Context, b *entity.Branch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBranchRepositoryMockRecorder) Create(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBranchRepository)(nil).Create), ctx, b)
}

// FindByID mocks base method.
func (m *MockBranchRepository) FindByID(ctx context.Context, businessID, id uuid.UUID) (*entity.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, businessID, id)
	ret0, _ := ret[0].(*entity.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBranchRepositoryMockRecorder) FindByID(ctx, businessID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBranchRepository)(nil).FindByID), ctx, businessID, id)
}

// FindDefault mocks base method.
func (m *MockBranchRepository) FindDefault(ctx context.Context, businessID uuid.UUID) (*entity.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDefault", ctx, businessID)
	ret0, _ := ret[0].(*entity.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDefault indicates an expected call of FindDefault.
func (mr *MockBranchRepositoryMockRecorder) FindDefault(ctx, businessID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDefault", reflect.TypeOf((*MockBranchRepository)(nil).FindDefault), ctx, businessID)
}

// ListByBusiness mocks base method.
func (m *MockBranchRepository) ListByBusiness(ctx context.Context, businessID uuid.UUID) ([]entity.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBusiness", ctx, businessID)
	ret0, _ := ret[0].([]entity.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBusiness indicates an expected call of ListByBusiness.
func (mr *MockBranchRepositoryMockRecorder) ListByBusiness(ctx, businessID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBusiness", reflect.TypeOf((*MockBranchRepository)(nil).ListByBusiness), ctx, businessID)
}
