// Code generated by MockGen. DO NOT EDIT.
// Source: business_repository.go
//
// Generated by this command:
//
//	mockgen -source=business_repository.go -destination=mocks/business_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/SandaruwanWeerawardhana/pos-backend/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBusinessRepository is a mock of BusinessRepository interface.
type MockBusinessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessRepositoryMockRecorder
	isgomock struct{}
}

// MockBusinessRepositoryMockRecorder is the mock recorder for MockBusinessRepository.
type MockBusinessRepositoryMockRecorder struct {
	mock *MockBusinessRepository
}

// NewMockBusinessRepository creates a new mock instance.
func NewMockBusinessRepository(ctrl *gomock.Controller) *MockBusinessRepository {
	mock := &MockBusinessRepository{ctrl: ctrl}
	mock.recorder = &MockBusinessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessRepository) EXPECT() *MockBusinessRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBusinessRepository) Create(ctx context.Context, b *entity.Business) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBusinessRepositoryMockRecorder) Create(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBusinessRepository)(nil).Create), ctx, b)
}

// ExistsBySlug mocks base method.
func (m *MockBusinessRepository) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBySlug", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBySlug indicates an expected call of ExistsBySlug.
func (mr *MockBusinessRepositoryMockRecorder) ExistsBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBySlug", reflect.TypeOf((*MockBusinessRepository)(nil).ExistsBySlug), ctx, slug)
}

// FindByID mocks base method.
func (m *MockBusinessRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBusinessRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBusinessRepository)(nil).FindByID), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockBusinessRepository) FindBySlug(ctx context.Context, slug string) (*entity.Business, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Business)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockBusinessRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockBusinessRepository)(nil).FindBySlug), ctx, slug)
}

// SetOwner mocks base method.
func (m *MockBusinessRepository) SetOwner(ctx context.Context, businessID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwner", ctx, businessID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwner indicates an expected call of SetOwner.
func (mr *MockBusinessRepositoryMockRecorder) SetOwner(ctx, businessID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwner", reflect.TypeOf((*MockBusinessRepository)(nil).SetOwner), ctx, businessID, userID)
}

// Update mocks base method.
func (m *MockBusinessRepository) Update(ctx context.Context, b *entity.Business) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBusinessRepositoryMockRecorder) Update(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBusinessRepository)(nil).Update), ctx, b)
}
