package repository

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"github.com/SandaruwanWeerawardhana/pos-backend/internal/entity"
)

//go:generate go run go.uber.org/mock/mockgen -source=product_repository.go -destination=mocks/product_repository_mock.go -package=mocks

// ErrAlreadyExists means a product with this id is already stored. The id is
// generated by the till, so this is the expected outcome of a replayed push
// (the first response was lost, the client retried) rather than a failure — the
// caller reports it as success.
var ErrAlreadyExists = errors.New("repository: product already exists")

// ProductRepository reads and writes the catalogue.
type ProductRepository interface {
	// ListForBusiness returns the full catalogue with batches preloaded. The
	// client caches it wholesale in IndexedDB, so this is deliberately not
	// paginated: a partial page would leave the till unable to sell whatever
	// was cut off.
	ListForBusiness(ctx context.Context, businessID uuid.UUID) ([]entity.Product, error)
	// FindManyByID loads a subset in one query, for order sync resolving the
	// products named by a batch of sold lines.
	FindManyByID(ctx context.Context, businessID uuid.UUID, ids []uuid.UUID) ([]entity.Product, error)
	// FindByIdentifier returns the product holding this SKU or barcode within a
	// business, so a genuine clash can be reported before the unique index
	// rejects the insert with a driver error nothing above can interpret.
	FindByIdentifier(ctx context.Context, businessID uuid.UUID, sku, barcode string) (*entity.Product, error)
	// Create stores a product and its opening batches, returning
	// ErrAlreadyExists if a product with the same id is already stored.
	Create(ctx context.Context, p *entity.Product) error
	// FindByID loads one product, scoped to its business. Returns ErrNotFound
	// for a missing id and for another tenant's id alike — the caller must map
	// both to 404, never 403, or it leaks that the product exists.
	FindByID(ctx context.Context, businessID, id uuid.UUID) (*entity.Product, error)
	// Update writes the product's catalogue columns back. Stock, batches and
	// the ownership columns are not touched.
	Update(ctx context.Context, p *entity.Product) error
	// Delete soft-deletes the product. The row survives so historical order
	// items still resolve a name and price, while the partial unique indexes
	// (WHERE deleted_at IS NULL) free the SKU and barcode for reuse.
	Delete(ctx context.Context, businessID, id uuid.UUID) error
}

type productRepository struct {
	db *gorm.DB
}

func NewProductRepository(db *gorm.DB) ProductRepository {
	return &productRepository{db: db}
}

func (r *productRepository) ListForBusiness(ctx context.Context, businessID uuid.UUID) ([]entity.Product, error) {
	var products []entity.Product
	err := r.db.WithContext(ctx).
		Preload("Batches").
		Where("business_id = ?", businessID).
		Order("name").
		Find(&products).Error
	return products, err
}

func (r *productRepository) FindManyByID(ctx context.Context, businessID uuid.UUID, ids []uuid.UUID) ([]entity.Product, error) {
	if len(ids) == 0 {
		return []entity.Product{}, nil
	}
	var products []entity.Product
	err := r.db.WithContext(ctx).
		Where("business_id = ? AND id IN ?", businessID, ids).
		Find(&products).Error
	return products, err
}

func (r *productRepository) FindByIdentifier(ctx context.Context, businessID uuid.UUID, sku, barcode string) (*entity.Product, error) {
	var product entity.Product
	err := r.db.WithContext(ctx).
		Where("business_id = ? AND (sku = ? OR barcode = ?)", businessID, sku, barcode).
		First(&product).Error
	if err != nil {
		return nil, wrapNotFound(err)
	}
	return &product, nil
}

// Create inserts the product and its batches in one transaction, so a product
// that tracks expiry is never stored without the opening batch its expiry
// reports read from.
//
// DoNothing on the primary-key conflict rather than letting the insert error:
// the till generates the id, so a replay is an expected outcome and telling it
// apart from a real failure by parsing driver error strings would be fragile.
// RowsAffected == 0 is the signal — the same approach
// orderRepository.InsertIfNew uses for client_generated_id.
func (r *productRepository) Create(ctx context.Context, p *entity.Product) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		res := tx.
			Omit("Batches").
			Clauses(clause.OnConflict{
				Columns:   []clause.Column{{Name: "id"}},
				DoNothing: true,
			}).
			Create(p)
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected == 0 {
			return ErrAlreadyExists
		}

		if len(p.Batches) == 0 {
			return nil
		}
		for i := range p.Batches {
			p.Batches[i].ProductID = p.ID
		}
		return tx.Create(&p.Batches).Error
	})
}

func (r *productRepository) FindByID(ctx context.Context, businessID, id uuid.UUID) (*entity.Product, error) {
	var product entity.Product
	err := r.db.WithContext(ctx).
		Preload("Batches").
		Where("business_id = ? AND id = ?", businessID, id).
		First(&product).Error
	if err != nil {
		return nil, wrapNotFound(err)
	}
	return &product, nil
}

// Update writes an explicit column map rather than saving the struct.
//
// Two reasons, both load-bearing. Saving the struct would write stock_quantity
// back from whatever the loaded copy held, undoing any deduction order sync
// made between the read and this write. And a struct update skips zero values,
// so a cleared brand or a price of 0 would be silently dropped — a map assigns
// every listed column, nil pointers included, which is what makes an omitted
// optional field actually clear the column.
//
// updated_at is left to the products_set_updated_at trigger.
func (r *productRepository) Update(ctx context.Context, p *entity.Product) error {
	columns := map[string]any{
		"name":             p.Name,
		"sku":              p.SKU,
		"barcode":          p.Barcode,
		"barcode_source":   p.BarcodeSource,
		"price_cents":      p.PriceCents,
		"cost_cents":       p.CostCents,
		"tax_rate":         p.TaxRate,
		"category":         p.Category,
		"brand":            p.Brand,
		"description":      p.Description,
		"unit":             p.Unit,
		"status":           p.Status,
		"is_weighted":      p.IsWeighted,
		"reorder_level":    p.ReorderLevel,
		"min_stock_level":  p.MinStockLevel,
		"discount_percent": p.DiscountPercent,
		"shelf_location":   p.ShelfLocation,
		"image_url":        p.ImageURL,
		"images":           p.Images,
		"plugin_data":      p.PluginData,
		"supplier_id":      p.SupplierID,
	}

	res := r.db.WithContext(ctx).
		Model(&entity.Product{}).
		Where("business_id = ? AND id = ?", p.BusinessID, p.ID).
		Updates(columns)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return ErrNotFound
	}
	return nil
}

func (r *productRepository) Delete(ctx context.Context, businessID, id uuid.UUID) error {
	res := r.db.WithContext(ctx).
		Where("business_id = ? AND id = ?", businessID, id).
		Delete(&entity.Product{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return ErrNotFound
	}
	return nil
}
